modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/OreCruncher/DynamicSurroundings2/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-soundcontrol"
logoFile="logo.png"

[[mods]]
	modId="sndctrl"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eSound Control"
	updateJSONURL="https://raw.githubusercontent.com/OreCruncher/DynamicSurroundings2/master/version.json"
	credits="\n\n§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r\n§6SonicEther§r for making §2SoundPhysics§r GPL3\n"
	authors="§6OreCruncher§r\n"
	description="\nGiving the player §6control§r over their §2Minecraft§r §6sound experience§r."
	
	[[dependencies.sndctrl]]
		modId="forge"
		mandatory=true
		versionRange="[31.2.44,)"
		ordering="NONE"
		side="CLIENT"

[[mods]]
	modId="environs"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eEnvirons"
	updateJSONURL="https://raw.githubusercontent.com/OreCruncher/DynamicSurroundings2/master/version.json"
	credits="\n\n§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r\n"
	authors="§6OreCruncher§r\n"
	description="\nAdds §6sound§r and §6visual§r effects to §6biomes§r"
	
	[[dependencies.environs]]
		modId="forge"
		mandatory=true
		versionRange="[31.2.4,)"
		ordering="NONE"
		side="CLIENT"

	[[dependencies.environs]]
		modId="sndctrl"
		mandatory=true
		versionRange="[1.15.2-1.0.0.1,)"
		ordering="AFTER"
		side="CLIENT"

[[mods]]
	modId="mobeffects"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eMob Effects"
	updateJSONURL="https://raw.githubusercontent.com/OreCruncher/DynamicSurroundings2/master/version.json"
	credits="\n\n§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r\n"
	authors="§6OreCruncher§r\n"
	description="\nGiving §6mobs§r special §6effects§r."
	
	[[dependencies.mobeffects]]
		modId="forge"
		mandatory=true
		versionRange="[31.2.44,)"
		ordering="NONE"
		side="CLIENT"

	[[dependencies.mobeffects]]
		modId="sndctrl"
		mandatory=true
		versionRange="[1.15.2-1.0.0.1,)"
		ordering="AFTER"
		side="CLIENT"