modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/OreCruncher/DynamicSurroundings/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings"
logoFile="logo.png"
license = "GPL-3.0"
showAsResourcePack=false

[[mods]]
	modId="dsurround"
	version="${version}"
	displayName="3Dynamic Surroundings"
	updateJSONURL="https://raw.githubusercontent.com/OreCruncher/DynamicSurroundings2/master/version.json"
	credits="  Wirsbor for 2BetterRainr SonicEtherr for 2Sound Physicsr MrRuber for 2Aurora Rubealisr Hurricaaaner for 2Presence Footstepsr and 2MAtmosr eSound and Texture Attributionsr at https://tinyurl.com/mggnl76  "
	authors="OreCruncherr "
	description=" Adds a variety of soundr and visualr effects to improve your Minecraft experience"

	[[dependencies.dsurround]]
		modId="forge"
		mandatory=true
		versionRange="[36.2.0,)"
		ordering="NONE"
		side="CLIENT"

	[[dependencies.dsurround]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.5,)"
		ordering="NONE"
		side="CLIENT"

[[mods]]
	modId="sndctrl"
	version="${version}"
	displayName="3Dynamic Surroundings: eSound Control"
	credits="  All the Playersr that installed and enjoyed 2Dynamic Surroundingsr SonicEtherr for making 2SoundPhysicsr GPL3 "
	authors="OreCruncherr "
	description=" Enhances and gives the player controlr over their 2Minecraftr sound experiencer."

	[[dependencies.sndctrl]]
		modId="dsurround"
		mandatory=false
		versionRange="[1.16.5,)"
		ordering="AFTER"
		side="CLIENT"
	
[[mods]]
	modId="environs"
	version="${version}"
	displayName="3Dynamic Surroundings: eEnvirons"
	credits="  All the Playersr that installed and enjoyed 2Dynamic Surroundingsr "
	authors="OreCruncherr "
	description=" Adds soundr and visualr effects to biomesr"
	
	[[dependencies.environs]]
		modId="sndctrl"
		mandatory=false
		versionRange="[1.16.5,)"
		ordering="AFTER"
		side="CLIENT"

[[mods]]
	modId="mobeffects"
	version="${version}"
	displayName="3Dynamic Surroundings: eMob Effects"
	credits="  All the Playersr that installed and enjoyed 2Dynamic Surroundingsr "
	authors="OreCruncherr "
	description=" Giving mobsr and playersr special soundr and visualr effects."
	
	[[dependencies.mobeffects]]
		modId="sndctrl"
		mandatory=false
		versionRange="[1.16.5,)"
		ordering="AFTER"
		side="CLIENT"